env:
  global:
    - VERSION=0.46
  matrix:
    - DOCKER_BUILD_DIR=./python-2.7
      IMAGE_NAME=dockerrepository/zappa:2.7
    - DOCKER_BUILD_DIR=./python-3.6
      IMAGE_NAME=dockerrepository/zappa:3.6

sudo: required
language: bash
services:
  - docker

deploy:
  provider: script
  script: bash deploy_image.sh
  on:
    branch:
      - master

notifications:
  email: false